---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/9 21:33
---

-- 默认扫描路径
print(package.cpath)

-- 修改默认操作路径
--package.path = package.path .. ";/Users/kail/IdeaProjects/github/hello-world-example/Lua/src/main/lua/module/?.lua"
print(package.path)

--package.preload["module"] = "/Users/kail/IdeaProjects/github/hello-world-example/Lua/src/main/lua/module/module.lua"

local module = require("module`")



print(moduleconstant)
module.func3()

print(os.getenv(""))