---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/12/1 10:58
---

-- metatable
local def_init = {
    __call = function(my_table, new_table)
        if not new_table then
            return my_table
        end
        my_table.name = new_table.name
        return my_table;
    end
}

-- 原始 table
local my_table = { name = "kai" }

setmetatable(my_table, def_init)

local t1 = my_table()
print(t1.name)

local t2 = my_table({ name = "kkk" })
print(t1.name)
print(t2.name)