---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/12/1 10:58
---

-- metatable
local my_parent_metatable = {
    name = "new",
    nick = "kailbin",
    getAge = function()
        return 28
    end
}

-- 原始 table
local my_table = {
    name = "kai",
}

setmetatable(my_table, { __index = my_parent_metatable })

print(my_table.name)
print(my_table.nick)
print(my_table.getAge())

for k, v in pairs(my_table) do
    print(k, v)
end
