---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/12/1 10:58
---

-- 原始 table
local my_table = { name = "kai" }
local new_table = {}
setmetatable(my_table, { __newindex = new_table })

my_table.nick = "kailbin"
print(my_table.nick, new_table.nick)

my_table.name = "Kail"
print(my_table.name, new_table.name)


-- 原始 table
my_table = { name = "kai" }
meta_filter_table = {
    __newindex = function(my_tab, key, value)
        my_tab[key] = value .. "!"
        --rawset(my_table, key, value .. "!")
    end
}
setmetatable(my_table, meta_filter_table)

my_table.nick = "kailbin"
print(my_table.nick)

my_table.name = "Kail"
print(my_table.name)
