---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/12/1 10:58
---

-- metatable function
local my_invoker = function(target, methodKey)
    if methodKey == "getAge" then
        return 28
    else
        return methodKey
    end
end

-- 原始 table
local my_table = {
    name = "kai",
}

setmetatable(my_table, { __index = my_invoker })

print(my_table.name)
print(my_table.getAge)
print(my_table.getAge1)
print(my_table.getAge())
