---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/12/1 09:44
---
local Object = require("Object")

Point = Object:extend()

function Point:new(x, y)
    self.x = x or 0
    self.y = y or 0
end

local p = Point(10, 20)

print(p.x)
print(p.y)