---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/9 16:19
---

print(string.format("the %s is : %d", "value", 4))

print(utf8.len("中文"))
print(utf8.len("abc"))

print(string.rep("abc", 2))  --> abcabc

print(string.char(97, 98, 99))

print(string.byte("abc", 2))

print(string.upper("杨凯彬"))

str, count = string.gsub("燕燕燕", "燕", "子")
print(str, count)

print(string.find("abc", "bc"))

str = "大闹天宫"
startI, endI = string.find("大闹天宫", "闹 天")
print(startI, endI)
print(string.sub("大闹天宫", string.find(str, "闹天")))

print(string.match("I have 2 questions", "%d+ %a+"))

for word in string.gmatch("Hello Lua user", "%a+") do
    print(word)
end

print(string.format("%u, %f", -1, 1))