---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/9 15:42
---

s1 = "this is string1"
s2 = 'this is string2'

s3 = [[这是
多行字符串
]]

print(#s3)
print(string.len(s3))
print(utf8.len(s3))

print("utf8.codes")
for p, c in utf8.codes(s3) do
    print(p, string.char(c))
end