---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/9 00:11
---

function return2()
    return 1, 2
end

a, b = return2()
print(a, b)

function average(...)
    local arg = { ... }

    result = 0
    for i, v in pairs(arg) do
        result = result + v
    end
    print("总共传入 " .. #arg .. " 个数")
    return result / #arg
end

print("平均值", average(1, 2, 3))

function foo(...)
    -- select('#', ...) 获取可变参数长度
    for i = 1, select('#', ...) do
        -- 读取可变参数索引
        local arg = select(i, ...);
        print("arg", arg);
    end
end

foo(1, "2", nil, 4);