---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/8 18:48
---

--[[
多行注释
--]]

do
    local a = 6     -- 局部变量
    var = 6         -- 全局变量
    print(a, var);  -- 6 6
end

print("Hi! I am Emmy.asd")

world = "World"
print("Hello " .. world)

local array = { "apple", "pear", "orange", "grape" }
print(array[0])
print(array[1])
print(array[4])

for i, v in ipairs(array) do
    print(i .. " " .. v)
end

array[7] = "seven"
for k, v in pairs(array) do
    print(k .. " " .. v)
end

array[1] = nil
for k, v in pairs(array) do
    print(k .. " " .. v)
end
for i, v in ipairs(array) do
    print(i .. " " .. v)
end
--
--for k, v in pairs(table) do
--    print(k .. " : " .. v)
--end

local dict = {
    key1 = "value1",
    key2 = "value2",
}
print(dict.key1)
print(dict['key1'])
for k, v in pairs(dict) do
    print(k .. " : " .. v)
end

function fun1(n)
    if n == 0 then
        return 0
    else
        return n + fun1(n - 1)
    end
end

print(fun1(5))

fun2 = fun1
print(fun2(5))

