---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/9 00:08
---

i = 1
if i == 0 then
    print("零")
elseif i == 1 then
    print("壹")
else
    print("-")
end

a = false
b = true
c = false

if not (a and b) or c then
    print("not (a and b) or c -->", true)
end