---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/8/8 23:54
---

local i = 0
while (i < 10) do
    i = i + 1
end
-- print(i)

for i = 10, 1, -1 do
    print(i)
end

for i = 0, 10, 1 do
    print(i)
end

for i = 10, 1, -1 do
    print(i)
end

a = 0
repeat
    a = a + 1
until (a > 15)

while (true) do
    i = i + 1
    if (i > 10) then
        break
    end
end

print("Goto")
for i = 0, 10 do
    if i % 2 == 0 then
        goto continue
    end
    print(i)
    -- label 的定义
    :: continue ::
end

