---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by kail.
--- DateTime: 2020/11/27 15:16
---

hello = require("module/hello")
helloRock = require("hello-rock")

hello.sayHello()
hello.say("Kail")

helloRock.sayHello()
helloRock.say("Kail")